title: Ethical Compass
email: intelligence@ethicalcompass.ai
description: >-
  A strategic platform for institutional accountability and proactive ethical oversight.
baseurl: "/ethical-compass"
url: "https://yesafrikaweb.github.io"

# Collections
collections:
  modules:
    output: true
    permalink: /modules/:path/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .cursorrules
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
